name = "FractionalSystems"
uuid = "43fecb94-217b-4542-9f6a-a624b53b7d19"
authors = ["Qingyu Qu <erikqqy123@gmail.com>"]
version = "0.1.3"

[deps]
ControlSystemIdentification = "3abffc1c-5106-53b7-b354-a47bfc086282"
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
FractionalDiffEq = "c7492dd8-6170-483b-af64-cefb6c377d9a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
ControlSystemIdentification = "2.2.4"
ControlSystems = "0.11, 0.12"
FractionalDiffEq = "0.2"
Roots = "1.3.14, 2"
SpecialFunctions = "2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
